project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

execute: 
  freeze: auto

website:
  title: "L. McKinley Nevins"
  repo-url: https://github.com/lmnevins/lmnevins.github.io
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: index.qmd
      - text: "Publications"
        href: index.qmd
      - text: "CV"
        href: index.qmd
      - text: "Extracurriculars"
        href: index.qmd
      - text: "Contact"
        href: index.qmd
        
    right: 
      - icon: github
        href: https://github.com/lmnevins
  page-footer: 
    center: "Copyright 2025, L. McKinley Nevins"
    background: secondary

format:
  html:
    toc: true
    link-external-newwindow: true
    link-external-icon: false